Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_25_BE, pull requests merged in 2024-03, with the labels that each got.

#2 👷 [CI/CD]: CICD 파이프라인 구축
  .github/workflows/dev_deploy.yml
  Dockerrun.aws.json
  build.gradle
  src/main/java/com/goormthonuniv/ownearth/controller/RootController.java
  src/main/java/com/goormthonuniv/ownearth/domain/Item.java
  src/main/java/com/goormthonuniv/ownearth/domain/Member.java
  src/main/java/com/goormthonuniv/ownearth/domain/Mission.java
  src/main/java/com/goormthonuniv/ownearth/domain/common/BaseEntity.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/FriendStatus.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/ItemCategory.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/MissionCategory.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/SocialType.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/Friend.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberItem.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/resources/application.yml
Labels: bugfix, featrue, infra

#6 ✨ [Feat]: 시큐리티 관련 설정
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/Friend.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberItem.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Password.java
  src/main/java/com/goormthonuniv/ownearth/exception/AuthException.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/exception/MemberException.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberRepository.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/java/com/goormthonuniv/ownearth/security/domain/MemberDetails.java
  src/main/java/com/goormthonuniv/ownearth/security/filter/JwtAuthExceptionHandlingFilter.java
  src/main/java/com/goormthonuniv/ownearth/security/filter/JwtRequestFilter.java
  src/main/java/com/goormthonuniv/ownearth/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/goormthonuniv/ownearth/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/goormthonuniv/ownearth/security/provider/JwtAuthProvider.java
  src/main/java/com/goormthonuniv/ownearth/security/service/MemberDetailsService.java
Labels: featrue, infra

#8 :sparkles: [Feat]: AuthMember Argument Resolver 구현
  src/main/java/com/goormthonuniv/ownearth/annotation/auth/AuthMember.java
  src/main/java/com/goormthonuniv/ownearth/annotation/auth/AuthMemberArgumentResolver.java
  src/main/java/com/goormthonuniv/ownearth/config/WebConfig.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue, infra

#10 :sparkles: [Feat]: S3 파일 관리 클래스 구현
  src/main/java/com/goormthonuniv/ownearth/aws/s3/S3Client.java
  src/main/java/com/goormthonuniv/ownearth/aws/s3/S3Directory.java
  src/main/java/com/goormthonuniv/ownearth/config/AmazonConfig.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/exception/S3Exception.java
Labels: featrue, infra

#13 ✨ [Feat]: OpenAI Feign Client 구성
  build.gradle
  src/main/java/com/goormthonuniv/ownearth/OwnEarthApplication.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/OpenAiClientConfig.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/dto/MissionImageAnalysisRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/dto/MissionImageAnalysisResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/service/OpenAiClient.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: featrue

#15 :sparkles: [FEAT]: Member 회원가입 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Password.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MemberRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberRepository.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#17 :sparkles:[Feat]: Member 로그인 로직 구현
  src/main/java/com/goormthonuniv/ownearth/common/BaseResponse.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/Item.java
  src/main/java/com/goormthonuniv/ownearth/domain/Mission.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Password.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MemberRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalExceptionHandler.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/java/com/goormthonuniv/ownearth/security/filter/JwtAuthExceptionHandlingFilter.java
  src/main/java/com/goormthonuniv/ownearth/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/goormthonuniv/ownearth/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#19 :sparkles:[Feat]: MemberMission 오늘의 미션 조회/할당 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/MemberMissionException.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberMissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/repository/MissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MissionCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
Labels: featrue

#21 ✨ [Feat]: 미션 수행 API 구현
  src/main/java/com/goormthonuniv/ownearth/common/BaseResponse.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/MissionCategory.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MissionRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalExceptionHandler.java
  src/main/java/com/goormthonuniv/ownearth/exception/MissionException.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/dto/MissionImageAnalysisRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberMissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MissionCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
Labels: docs, featrue

#22 :sparkles:[Feat]: MemberMission Mission변경 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/Mission.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberMission.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/exception/MemberMissionException.java
  src/main/java/com/goormthonuniv/ownearth/exception/MissionException.java
  src/main/java/com/goormthonuniv/ownearth/service/MissionCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
Labels: featrue

#26 :sparkles: [Feat]: 내 월간 달성률 조회 API 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberMissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#32 ✨ [Feat]: 완료한 미션 목록 조회 API 구현
  src/main/java/com/goormthonuniv/ownearth/config/SwaggerConfig.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberMissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#30 ✨ [Feat]: 내 친구 월간 달성률 조회 API
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/FriendStatus.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/Friend.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/repository/FriendRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#34 :sparkles: [Feat]: 친구 요청 API 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/Friend.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/repository/FriendRepository.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: bugfix, featrue

#36 ✨ [Feat]: 친구 요청 수락/거절 API 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/Friend.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MemberRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#40 ✨ [Feat]: 친구 요청 목록 조회 API
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/FriendRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#39 :sparkles:[Feat]: 포인트 조회 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#44 :sparkles:[Feat]: 아이템 목록 조회 구현
  src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/ItemCategory.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/ItemResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/ItemRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/ItemQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberItemCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/ItemQueryServiceImpl.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberItemCommandServiceImpl.java
Labels: featrue

#47 ✨ [Feat]: 회원 검색 API 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
  src/main/resources/application.yml
Labels: featrue

#49 :sparkles:[Feat]: 아이템 구매 구현
  src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberItem.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/ItemResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/exception/ItemException.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberItemRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/ItemCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/ItemCommandServiceImpl.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#50 :sparkles: [Feat]: 아이템 사용/해제 토글 API 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/mapping/MemberItem.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#52 :sparkles:[Feat]: 친구 정보 조회 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/FriendRepository.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberItemRepository.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberMissionRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberItemCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberItemCommandServiceImpl.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#54 :bug: [Fix]: 친구 추가 올바르게 되지 않던 문제 해결
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#56 :sparkles:[Feat]: reissue 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MemberRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/security/SecurityConfig.java
  src/main/java/com/goormthonuniv/ownearth/security/provider/JwtAuthProvider.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#58 :recycle:[Refactor]: 지구 상태 조회 수정
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/ItemCategory.java
  src/main/java/com/goormthonuniv/ownearth/domain/enums/MissionCategory.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#59 ✨[Feat]: 보유 아이템 조회 구현
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/ItemResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberItemRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#61 :recycle:[Refactor]: 회원가입/지구 이름설정 분리
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/member/Member.java
  src/main/java/com/goormthonuniv/ownearth/dto/request/MemberRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/exception/GlobalErrorCode.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberCommandService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberCommandServiceImpl.java
Labels: featrue

#65 :recycle:[Refactor]: 계정 만든 기간 수정
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: refactor

#67 :recycle: [Refactor]: 미션 DTO 통합
  src/main/java/com/goormthonuniv/ownearth/controller/MissionController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
Labels: refactor

#69 🐛[Fix]: 오늘의 미션 할당/조회 반환값 수정
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
Labels: bugfix, refactor

#71 🐛 [Fix]: 미션 응답 수정 및 nginx 설정 구성
  .platform/nginx.conf
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
Labels: featrue

#77 ♻️[Refactor]: 아이템 조회 수정
  src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/Item.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/ItemResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/repository/MemberItemRepository.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: refactor

#79 :recycle:[Refactor]: 아이템 url 반환 변경
  src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/domain/Item.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: refactor

#81 :recycle:[Refactor]: 지구 상태 조회 변경
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: refactor

#83 ♻️ [Refactor]: AI 프롬프트 엔지니어링, 로직, 클래스 구조 변경
  src/main/java/com/goormthonuniv/ownearth/feign/openai/Prompt.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/dto/MissionImageAnalysisRequestDto.java
  src/main/java/com/goormthonuniv/ownearth/feign/openai/dto/MissionImageAnalysisResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
  src/main/resources/application.yml
Labels: refactor

#84 :recycle:[Refactor]: 보유 아이템 조회 변경
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: refactor

#86 :bug:[Fix]:엔드포인트 수정
  src/main/java/com/goormthonuniv/ownearth/controller/ItemController.java
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
Labels: bugfix

#88 :bug:[Fix]: MyInventory 반환 수정
  src/main/java/com/goormthonuniv/ownearth/converter/ItemConverter.java
Labels: bugfix

#90 :sparkles:[Feat]: 친구 목록 조회
  src/main/java/com/goormthonuniv/ownearth/controller/MemberController.java
  src/main/java/com/goormthonuniv/ownearth/converter/MemberConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MemberResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/MemberQueryService.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MemberQueryServiceImpl.java
Labels: featrue

#93 ♻️ :[Refactor]: 미션 할당/조회 수정
  src/main/java/com/goormthonuniv/ownearth/converter/MissionConverter.java
  src/main/java/com/goormthonuniv/ownearth/dto/response/MissionResponseDto.java
  src/main/java/com/goormthonuniv/ownearth/service/impl/MissionCommandServiceImpl.java
Labels: refactor
